[project]
name = "openalex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyalex>=0.18",
    "tqdm>=4.67.1",
]

[tool.pyright]
exclude = [".venv"]
venvPath = "."
venv = ".venv"
